import {
  markdownToPlainText,
  markdownToSummaryText,
  renderMarkdown,
} from './markdown';

describe('renderMarkdown', () => {
  it('renders the subset a project description is allowed to use', () => {
    const html = renderMarkdown(
      '# Heading\n\nA **bold** and *italic* claim with `code`.\n\n- one\n- two\n\n1. first\n\n> quoted\n\n[link](https://example.com)',
    );

    expect(html).toContain('<h1>Heading</h1>');
    expect(html).toContain('<strong>bold</strong>');
    expect(html).toContain('<em>italic</em>');
    expect(html).toContain('<code>code</code>');
    expect(html).toContain('<ul>');
    expect(html).toContain('<ol>');
    expect(html).toContain('<blockquote>');
    expect(html).toContain('<a href="https://example.com">link</a>');
  });

  it('renders a fenced code block without interpreting what is inside it', () => {
    const html = renderMarkdown('```\nconst x = **not bold**;\n```');

    expect(html).toContain('<pre>');
    expect(html).toContain('<code>');
    // The marks survive as text. A renderer that let inline rules run inside a fence would turn
    // a code sample containing asterisks into something that no longer compiles when copied.
    expect(html).toContain('**not bold**');
    expect(html).not.toContain('<strong>');
  });

  it('escapes raw HTML instead of passing it through', () => {
    // `html: false`. This is the first of the two layers -- the second is Angular's [innerHTML]
    // sanitizer at the binding -- and it is the one this module is responsible for.
    const html = renderMarkdown('<script>window.pwned = true;</script>');

    expect(html).not.toContain('<script>');
    expect(html).toContain('&lt;script&gt;');
  });

  it('does not emit images, so the alt-text rules stay the only path to one', () => {
    // A project's pictures have their own `images` field, whose alt text is generated by
    // shared/project-image-alt (#87). An <img> reachable from a description would bypass that
    // entirely and arrive with whatever alt an admin happened to type, or none.
    const html = renderMarkdown('![alt text](https://example.com/x.png)');

    expect(html).not.toContain('<img');
    // What it degrades to, pinned because it is not obvious: disabling the `image` rule leaves the
    // `!` as a literal character, and the `[text](url)` behind it is still a perfectly good link.
    // So an admin who pastes image syntax gets a clickable link prefixed with "!" rather than
    // either a picture or an error. That is a reasonable landing place -- the URL stays reachable
    // -- but it is worth someone knowing before they wonder where the exclamation mark came from.
    expect(html).toContain('<a href="https://example.com/x.png">alt text</a>');
    expect(html).toContain('>!<');
  });

  it('leaves a bare URL as text', () => {
    // `linkify: false`. Descriptions cite repository paths, flags and hostnames; auto-linking
    // turns a fragment someone typed into a live link they did not write.
    const html = renderMarkdown('See https://example.com for details.');

    expect(html).not.toContain('<a ');
  });

  it('treats a single newline as a space rather than a line break', () => {
    // `breaks: false`. The seeded content wraps its source at column 100, so hard-breaking on
    // every newline would render each paragraph as a ragged column.
    const html = renderMarkdown('one\ntwo');

    expect(html).not.toContain('<br');
    expect(html).toContain('one\ntwo');
  });

  it('returns an empty string for a missing description rather than throwing', () => {
    expect(renderMarkdown(null)).toBe('');
    expect(renderMarkdown(undefined)).toBe('');
    expect(renderMarkdown('')).toBe('');
  });
});

describe('markdownToPlainText', () => {
  it('strips the marks and keeps the words', () => {
    const text = markdownToPlainText('## Heading\n\nA **bold** claim with `code`.');

    expect(text).toBe('Heading\n\nA bold claim with code.');
  });

  it('keeps blocks separated by a blank line, so the excerpt pipe can still find paragraphs', () => {
    // description-excerpt splits on a blank line to take the first paragraph. If flattening ran
    // the blocks together, the "first paragraph" would become the entire description.
    const text = markdownToPlainText('First para.\n\nSecond para.');

    expect(text.split(/\n\n/)).toEqual(['First para.', 'Second para.']);
  });

  it('separates list items, so a bulleted opener does not run into one word', () => {
    const text = markdownToPlainText('- alpha\n- beta');

    expect(text).toContain('alpha');
    expect(text).toContain('beta');
    expect(text).not.toContain('alphabeta');
  });

  it('unescapes what the renderer escaped, rather than leaking entities into a meta tag', () => {
    // The failure this pins is subtle and lands in search results: the renderer escapes `&` and
    // `<` on the way to HTML, and text that is never parsed as HTML again would otherwise carry
    // `&amp;` verbatim into <meta name="description">.
    expect(markdownToPlainText('Tools & toys')).toBe('Tools & toys');
    expect(markdownToPlainText('a < b')).toBe('a < b');
  });

  it('does not double-decode an entity that was written literally', () => {
    // `&amp;lt;` means the visible text "&lt;". Decoding twice would turn it into "<", inventing
    // markup characters in text that deliberately did not have them.
    expect(markdownToPlainText('&amp;lt;')).toBe('&lt;');
  });

  it('returns an empty string for a missing description', () => {
    expect(markdownToPlainText(null)).toBe('');
    expect(markdownToPlainText(undefined)).toBe('');
  });
});

describe('markdownToSummaryText', () => {
  it('drops headings, so a summary is the prose and not the section title', () => {
    // The defect this exists for was invisible to every other test here and was found by looking
    // at a rendered page: a description opening `## What it does` produced exactly that as the
    // whole <meta name="description">. Faithful flattening was working perfectly; taking the
    // first paragraph of it was the wrong thing to do with the result.
    const source = '## What it does\n\nA cross-platform equalizer.\n\n### Modules\n\n- one';

    expect(markdownToSummaryText(source).split(/\n\n/)[0]).toBe('A cross-platform equalizer.');
    // The faithful flattener still keeps them -- the two are meant to differ in exactly this way.
    expect(markdownToPlainText(source).split(/\n\n/)[0]).toBe('What it does');
  });

  it('summarises a description that is nothing but headings to nothing', () => {
    // Rather than to an arbitrary one of them. A caller that gets '' can skip the element; one
    // that gets a heading renders something misleading and cannot tell that it did.
    expect(markdownToSummaryText('# One\n\n## Two')).toBe('');
  });

  it('keeps everything that is not a heading', () => {
    const text = markdownToSummaryText('Intro.\n\n- alpha\n- beta\n\n> quoted');

    expect(text).toContain('Intro.');
    expect(text).toContain('alpha');
    expect(text).toContain('quoted');
  });
});
