// @ts-check
// ESLint for the frontend (#210). The ADR is docs/DECISIONS.md, 2026-10-01: angular-eslint's
// recommended sets as generated by `ng add angular-eslint`, plus one rule that is the reason this
// file exists. Run with `npm run lint`; CI runs the same.
const eslint = require('@eslint/js');
const { defineConfig } = require('eslint/config');
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');

/**
 * Each of these hands Angular a value its sanitizer will then trust as-is. Markdown is rendered by
 * shared/markdown/markdown.ts and bound through [innerHTML], and its safety rests on two layers:
 * markdown-it at `html: false`, and the sanitizer at the binding. One of these calls removes the
 * second layer, and no test notices -- the DOM assertions hold with either layer alone (#210). So
 * the guard is here, where it fails CI, rather than only in the three comments that warn about it.
 *
 * Not to be switched off with an eslint-disable comment. A real need for one means a decision,
 * recorded in docs/DECISIONS.md, that the value is trusted and why.
 */
const SANITIZER_BYPASS = [
  'bypassSecurityTrustHtml',
  'bypassSecurityTrustScript',
  'bypassSecurityTrustStyle',
  'bypassSecurityTrustUrl',
  'bypassSecurityTrustResourceUrl',
].map((property) => ({
  property,
  message:
    'Bypasses Angular\'s sanitizer, the second of the two layers that keep admin-authored ' +
    'Markdown from becoming XSS. See shared/markdown/markdown.ts and #210.',
}));

module.exports = defineConfig([
  // Generated from docs/openapi.yaml by openapi-generator and never edited by hand: a finding
  // there could only be fixed by changing the generator, and is regenerated away otherwise.
  { ignores: ['src/app/core/api/**'] },
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      '@angular-eslint/directive-selector': [
        'error',
        {
          type: 'attribute',
          prefix: 'app',
          style: 'camelCase',
        },
      ],
      '@angular-eslint/component-selector': [
        'error',
        {
          type: 'element',
          prefix: 'app',
          style: 'kebab-case',
        },
      ],
      'no-restricted-properties': ['error', ...SANITIZER_BYPASS],
    },
  },
  {
    // A stub standing in for a browser API (a canvas context, say) has methods whose whole job is
    // to do nothing.
    files: ['**/*.spec.ts'],
    rules: {
      '@typescript-eslint/no-empty-function': 'off',
    },
  },
  {
    files: ['**/*.html'],
    extends: [angular.configs.templateRecommended, angular.configs.templateAccessibility],
    rules: {},
  },
]);
