// @ts-check
// ESLint for the frontend (#210). The ADR is docs/DECISIONS.md, 2026-10-01: angular-eslint's
// recommended sets as generated by `ng add angular-eslint`, plus the rules that are the reason this
// file exists. Run with `npm run lint`; CI runs the same.
const eslint = require('@eslint/js');
const { defineConfig } = require('eslint/config');
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');

const SANITIZER_MESSAGE =
  'Bypasses Angular\'s sanitizer, the second of the two layers that keep admin-authored ' +
  'Markdown from becoming XSS. See shared/markdown/markdown.ts and #210.';

/**
 * Each of these hands Angular a value its sanitizer will then trust as-is. Markdown is rendered by
 * shared/markdown/markdown.ts and bound through [innerHTML], and its safety rests on two layers:
 * markdown-it at `html: false`, and the sanitizer at the binding. One of these calls removes the
 * second layer, and no test notices -- the DOM assertions hold with either layer alone (#210). So
 * the guard is here, where it fails CI, rather than only in the three comments that warn about it.
 *
 * Banned in templates too, by the HTML block below: `[innerHTML]="sanitizer.bypassSecurityTrustHtml(x)"`
 * is the same sink written in one line, and this property rule never sees template code.
 *
 * Not to be switched off with an eslint-disable comment. A real need for one means a decision,
 * recorded in docs/DECISIONS.md, that the value is trusted and why.
 */
const SANITIZER_BYPASS = [
  'bypassSecurityTrustHtml',
  'bypassSecurityTrustScript',
  'bypassSecurityTrustStyle',
  'bypassSecurityTrustUrl',
  'bypassSecurityTrustResourceUrl',
].map((property) => ({ property, message: SANITIZER_MESSAGE }));

/**
 * The same sink without Angular at all: an HTML string written straight into the DOM never reaches
 * the sanitizer. The codebase has none of these, so banning them costs nothing today. Reading
 * `outerHTML`, as some specs do, is not caught -- only writing it.
 */
const RAW_HTML_PROPERTIES = [
  { property: 'insertAdjacentHTML', message: SANITIZER_MESSAGE },
  { object: 'document', property: 'write', message: SANITIZER_MESSAGE },
];
const RAW_HTML_SYNTAX = [
  // el.innerHTML = x, and el['innerHTML'] = x
  'AssignmentExpression > MemberExpression.left[property.name=/^(inner|outer)HTML$/]',
  'AssignmentExpression > MemberExpression.left[property.value=/^(inner|outer)HTML$/]',
  // renderer.setProperty(el, 'innerHTML', x)
  "CallExpression[callee.property.name='setProperty'][arguments.1.value=/^(inner|outer)HTML$/]",
].map((selector) => ({ selector, message: SANITIZER_MESSAGE }));

module.exports = defineConfig([
  // Generated from docs/openapi.yaml by openapi-generator and never edited by hand: a finding
  // there could only be fixed by changing the generator, and is regenerated away otherwise.
  { ignores: ['src/app/core/api/**'] },
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      '@angular-eslint/directive-selector': [
        'error',
        {
          type: 'attribute',
          prefix: 'app',
          style: 'camelCase',
        },
      ],
      '@angular-eslint/component-selector': [
        'error',
        {
          type: 'element',
          prefix: 'app',
          style: 'kebab-case',
        },
      ],
      'no-restricted-properties': ['error', ...SANITIZER_BYPASS, ...RAW_HTML_PROPERTIES],
      'no-restricted-syntax': ['error', ...RAW_HTML_SYNTAX],
    },
  },
  {
    // A stub standing in for a browser API (a canvas context, say) has methods whose whole job is
    // to do nothing. Every spec, not only the one that has such a stub today.
    files: ['**/*.spec.ts'],
    rules: {
      '@typescript-eslint/no-empty-function': 'off',
    },
  },
  {
    // Inline templates arrive here too, extracted by processInlineTemplates above.
    files: ['**/*.html'],
    extends: [angular.configs.templateRecommended, angular.configs.templateAccessibility],
    rules: {
      // Template expressions are a separate AST, in which a bypass call is a node named after the
      // method, however it is reached (`sanitizer.x(...)`, `sanitizer?.x(...)`).
      'no-restricted-syntax': ['error', { selector: '[name=/^bypassSecurityTrust/]', message: SANITIZER_MESSAGE }],
    },
  },
]);
