/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AboutPage } from '../model/models';
import { AboutPageWriteRequest } from '../model/models';
import { ProblemDetail } from '../model/models';
import { ValidationProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface UpdateAboutPageRequestParams {
    aboutPageWriteRequest: AboutPageWriteRequest;
}


export interface AboutServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * The About page
     * Always answers 200. The row is created by the migration that adds the table (&#x60;V8&#x60;), so there is no state in which the page does not exist -- an unwritten page is one with an empty &#x60;body&#x60;, and the SPA renders a notice for that rather than a blank. That is what lets the frontend have no \&quot;not created yet\&quot; branch and the admin form no \&quot;create\&quot; mode. 
     * @endpoint get /about
*/
    getAboutPage(extraHttpRequestParams?: any): Observable<AboutPage>;

    /**
     * Replace the About page
     * Full replacement of the body, idempotent. There is deliberately no partial update, no draft state and no history: one page, one author, and every construct not built here is one fewer to secure. A singleton rather than a slug-keyed pages resource for the same reason -- see docs/DECISIONS.md, 2026-09-20. 
     * @endpoint put /about
* @param requestParameters
     */
    updateAboutPage(requestParameters: UpdateAboutPageRequestParams, extraHttpRequestParams?: any): Observable<AboutPage>;

}
