/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LoginRequest } from '../model/models';
import { LoginResponse } from '../model/models';
import { PasswordResetConfirmBody } from '../model/models';
import { PasswordResetRequestBody } from '../model/models';
import { PasswordResetValidateBody } from '../model/models';
import { ProblemDetail } from '../model/models';
import { ValidationProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ConfirmPasswordResetRequestParams {
    passwordResetConfirmBody: PasswordResetConfirmBody;
}

export interface LoginRequestParams {
    loginRequest: LoginRequest;
}

export interface RequestPasswordResetRequestParams {
    passwordResetRequestBody: PasswordResetRequestBody;
}

export interface ValidatePasswordResetTokenRequestParams {
    passwordResetValidateBody: PasswordResetValidateBody;
}


export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Complete a password reset using a token from the reset email
     * Public. Token must be unexpired and unused; consumed (used_at set) on success.
     * @endpoint post /auth/password-reset
* @param requestParameters
     */
    confirmPasswordReset(requestParameters: ConfirmPasswordResetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Admin login
     * Issues a JWT for the single AdminUser account, valid for 1 hour. No refresh-token endpoint -- re-login once the token expires.
     * @endpoint post /auth/login
* @param requestParameters
     */
    login(requestParameters: LoginRequestParams, extraHttpRequestParams?: any): Observable<LoginResponse>;

    /**
     * Request a password reset email
     * Public. Always returns 202 regardless of whether the email matches an AdminUser account, to avoid leaking account existence (email enumeration). If it matches, a single-use reset token is generated (30 minute expiry) and emailed via a transactional email API (Resend). 
     * @endpoint post /auth/password-reset-request
* @param requestParameters
     */
    requestPasswordReset(requestParameters: RequestPasswordResetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Check whether a password-reset token is still usable
     * Public. Answers whether a reset token is real, unused and unexpired, so the reset page can refuse to render a password form for a link that is already spent instead of letting the visitor compose a new password and only then discover the link is dead.  **A read, never a consume.** Unlike &#x60;POST /auth/password-reset&#x60;, this never sets &#x60;used_at&#x60;. Calling it any number of times leaves the token exactly as usable as it was -- which is the whole point, since the reset page calls it on load.  **POST with the token in the body, deliberately, not &#x60;GET ?token&#x3D;&#x60;.** The deployed backend sits behind Cloudflare and the provider\&#39;s nginx, both of which log request URLs, so a query string would write live reset tokens into two third parties\&#39; access logs. A body does not.  **Every failure looks the same.** Expired-but-unused, used-but-unexpired, never-issued and malformed tokens all return the same 400; the shape of the failure never says which. This endpoint is deliberately *not* enumeration-safe in the way &#x60;POST /auth/password-reset-request&#x60; is -- that one always answers 202 because its caller supplies an email address it may not own, whereas this caller already holds the token, and telling them whether their own link still works discloses nothing they could not learn by submitting the reset form itself. It is rate-limited per requester IP under its own bucket regardless, because it is a cheaper validity oracle than that form.  A token can still expire between this call and the reset submission, so a client must handle the submit path\&#39;s rejection too rather than treating a 204 here as a guarantee. 
     * @endpoint post /auth/password-reset/validate
* @param requestParameters
     */
    validatePasswordResetToken(requestParameters: ValidatePasswordResetTokenRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
