/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LoginRequest } from '../model/models';
import { LoginResponse } from '../model/models';
import { PasswordResetConfirmBody } from '../model/models';
import { PasswordResetRequestBody } from '../model/models';
import { ProblemDetail } from '../model/models';
import { ValidationProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ConfirmPasswordResetRequestParams {
    passwordResetConfirmBody: PasswordResetConfirmBody;
}

export interface LoginRequestParams {
    loginRequest: LoginRequest;
}

export interface RequestPasswordResetRequestParams {
    passwordResetRequestBody: PasswordResetRequestBody;
}


export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Complete a password reset using a token from the reset email
     * Public. Token must be unexpired and unused; consumed (used_at set) on success.
     * @endpoint post /auth/password-reset
* @param requestParameters
     */
    confirmPasswordReset(requestParameters: ConfirmPasswordResetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Admin login
     * Issues a JWT for the single AdminUser account, valid for 1 hour. No refresh-token endpoint -- re-login once the token expires.
     * @endpoint post /auth/login
* @param requestParameters
     */
    login(requestParameters: LoginRequestParams, extraHttpRequestParams?: any): Observable<LoginResponse>;

    /**
     * Request a password reset email
     * Public. Always returns 202 regardless of whether the email matches an AdminUser account, to avoid leaking account existence (email enumeration). If it matches, a single-use reset token is generated (30 minute expiry) and emailed via a transactional email API (Resend). 
     * @endpoint post /auth/password-reset-request
* @param requestParameters
     */
    requestPasswordReset(requestParameters: RequestPasswordResetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
