/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ContactMessage } from '../model/models';
import { ContactMessageAck } from '../model/models';
import { ContactMessagePageResponse } from '../model/models';
import { ContactMessageWriteRequest } from '../model/models';
import { ProblemDetail } from '../model/models';
import { ValidationProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface DeleteContactMessageRequestParams {
    id: string;
}

export interface GetContactMessageRequestParams {
    id: string;
}

export interface ListContactMessagesRequestParams {
    page?: number;
    size?: number;
}

export interface SubmitContactMessageRequestParams {
    contactMessageWriteRequest: ContactMessageWriteRequest;
}


export interface ContactServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Delete a contact message
     * Admin only.
     * @endpoint delete /contact-messages/{id}
* @param requestParameters
     */
    deleteContactMessage(requestParameters: DeleteContactMessageRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get a contact message by id
     * Admin only.
     * @endpoint get /contact-messages/{id}
* @param requestParameters
     */
    getContactMessage(requestParameters: GetContactMessageRequestParams, extraHttpRequestParams?: any): Observable<ContactMessage>;

    /**
     * List submitted contact messages
     * Admin only.
     * @endpoint get /contact-messages
* @param requestParameters
     */
    listContactMessages(requestParameters: ListContactMessagesRequestParams, extraHttpRequestParams?: any): Observable<ContactMessagePageResponse>;

    /**
     * Submit a contact form message
     * Public. Rate-limited per requester IP hash -- see docs/DATA_MODEL.md ContactMessage notes.
     * @endpoint post /contact
* @param requestParameters
     */
    submitContactMessage(requestParameters: SubmitContactMessageRequestParams, extraHttpRequestParams?: any): Observable<ContactMessageAck>;

}
