/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProblemDetail } from '../model/models';
import { Project } from '../model/models';
import { ProjectPageResponse } from '../model/models';
import { ProjectWriteRequest } from '../model/models';
import { ValidationProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateProjectRequestParams {
    projectWriteRequest: ProjectWriteRequest;
}

export interface DeleteProjectRequestParams {
    id: string;
}

export interface GetProjectRequestParams {
    id: string;
}

export interface ListProjectsRequestParams {
    page?: number;
    size?: number;
    tag?: Array<string>;
}

export interface UpdateProjectRequestParams {
    id: string;
    projectWriteRequest: ProjectWriteRequest;
}


export interface ProjectsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a project
     * 
     * @endpoint post /projects
* @param requestParameters
     */
    createProject(requestParameters: CreateProjectRequestParams, extraHttpRequestParams?: any): Observable<Project>;

    /**
     * Delete a project
     * 
     * @endpoint delete /projects/{id}
* @param requestParameters
     */
    deleteProject(requestParameters: DeleteProjectRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get a project by id
     * 
     * @endpoint get /projects/{id}
* @param requestParameters
     */
    getProject(requestParameters: GetProjectRequestParams, extraHttpRequestParams?: any): Observable<Project>;

    /**
     * List projects
     * Public, paginated, optionally filtered by tag (OR semantics across repeated &#x60;tag&#x60; params).
     * @endpoint get /projects
* @param requestParameters
     */
    listProjects(requestParameters: ListProjectsRequestParams, extraHttpRequestParams?: any): Observable<ProjectPageResponse>;

    /**
     * Replace a project (full update)
     * 
     * @endpoint put /projects/{id}
* @param requestParameters
     */
    updateProject(requestParameters: UpdateProjectRequestParams, extraHttpRequestParams?: any): Observable<Project>;

}
