/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Tag } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TagsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * List the tags currently attached to at least one published project
     * Read-only. Returns **only** tags attached to at least one **published** project, ordered by name ascending. This endpoint exists to populate the public \&quot;filter by tag\&quot; control, and offering a filter value that matches nothing is a dead end -- selecting it would return an empty project list on the site\&#39;s front page.  The \&quot;published\&quot; half of that is Phase 7a\&#39;s doing and follows from GET /projects filtering to published: a tag reachable only through an unpublished draft is exactly the dead-end filter value described above, and it additionally tells a visitor something about work that is not on the site yet. This is the same defect as the E2E-scaffolding tag that once reached the public filter, arriving by a new route.  Consequently the listing is derived, not stored: a tag drops out as soon as its last project is deleted (or stops referencing it), and comes back if a later project re-attaches the same name. Orphaned &#x60;tag&#x60; rows are deliberately *not* deleted when their last reference goes -- that would be a check-then-act write on state a concurrent project write may be attaching to at the same moment -- so the filtering happens here, on read. Stale rows in the table are invisible through the API.  Tags are created implicitly (upserted by name) when attached to a project via POST/PUT /projects -- there is no POST /tags.
     * @endpoint get /tags
*/
    listTags(extraHttpRequestParams?: any): Observable<Array<Tag>>;

}
