/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Tag } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TagsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * List all tags
     * Read-only. Tags are created implicitly (upserted by name) when attached to a project via POST/PUT /projects -- there is no POST /tags.
     * @endpoint get /tags
*/
    listTags(extraHttpRequestParams?: any): Observable<Array<Tag>>;

}
