/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { GithubWebhookAck } from '../model/githubWebhookAck';
// @ts-ignore
import { ProblemDetail } from '../model/problemDetail';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    WebhooksServiceInterface,
    ReceiveGithubWebhookRequestParams
} from './webhooks.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class WebhooksService extends BaseService implements WebhooksServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Receive a GitHub webhook delivery
     * Inbound-only, called by GitHub\&#39;s webhook infrastructure. No browser client calls this, and it takes no bearer token -- it is documented here anyway because this file is the contract for every HTTP endpoint the backend serves, and this is the one endpoint whose exact header names, verification scheme and status codes most need writing down, since the caller is a third party that cannot be asked to adapt.  **Verification.** GitHub computes HMAC-SHA256 over the *exact raw bytes* of the request body using the shared webhook secret and sends the result as &#x60;X-Hub-Signature-256: sha256&#x3D;&lt;hex&gt;&#x60;. The receiver verifies that signature over the untouched bytes before parsing anything. A missing, malformed, or non-matching signature is a 401 and nothing is recorded. Re-serialising a parsed body would change the bytes (whitespace and key order), so the signed representation is the only one that can be verified -- do not assume a semantically-equal payload will verify.  **Idempotency.** Deliveries are unique on &#x60;X-GitHub-Delivery&#x60;, and GitHub redelivers -- manually from the repository\&#39;s webhook settings, and automatically after some failures. A redelivered id is recorded exactly once: the replay answers 202 with &#x60;status: duplicate&#x60; and publishes no domain event.  **Feature flag.** Disabled by default. While &#x60;app.github-sync.enabled&#x60; is false this path is not mapped at all and answers 404, per CLAUDE.md\&#39;s config-based flags for Phase 7 extensions. When it is true, an unset webhook secret is a startup failure rather than a running receiver that cannot verify anything.  **Scope.** Phase 7a is the receiver only: verify, record, publish a &#x60;GithubDeliveryReceivedEvent&#x60;, stop. What a verified delivery should change on a Project is issue #54 and is deliberately not implemented -- the portfolio\&#39;s prose is hand-curated, so copying a repository description over it would destroy content. 
     * @endpoint post /webhooks/github
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public receiveGithubWebhook(requestParameters: ReceiveGithubWebhookRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<GithubWebhookAck>;
    public receiveGithubWebhook(requestParameters: ReceiveGithubWebhookRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<GithubWebhookAck>>;
    public receiveGithubWebhook(requestParameters: ReceiveGithubWebhookRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<GithubWebhookAck>>;
    public receiveGithubWebhook(requestParameters: ReceiveGithubWebhookRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const xHubSignature256 = requestParameters?.xHubSignature256;
        if (xHubSignature256 === null || xHubSignature256 === undefined) {
            throw new Error('Required parameter xHubSignature256 was null or undefined when calling receiveGithubWebhook.');
        }
        const xGitHubDelivery = requestParameters?.xGitHubDelivery;
        if (xGitHubDelivery === null || xGitHubDelivery === undefined) {
            throw new Error('Required parameter xGitHubDelivery was null or undefined when calling receiveGithubWebhook.');
        }
        const xGitHubEvent = requestParameters?.xGitHubEvent;
        if (xGitHubEvent === null || xGitHubEvent === undefined) {
            throw new Error('Required parameter xGitHubEvent was null or undefined when calling receiveGithubWebhook.');
        }
        const requestBody = requestParameters?.requestBody;
        if (requestBody === null || requestBody === undefined) {
            throw new Error('Required parameter requestBody was null or undefined when calling receiveGithubWebhook.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xHubSignature256 !== undefined && xHubSignature256 !== null) {
            localVarHeaders = localVarHeaders.set('X-Hub-Signature-256', String(xHubSignature256));
        }
        if (xGitHubDelivery !== undefined && xGitHubDelivery !== null) {
            localVarHeaders = localVarHeaders.set('X-GitHub-Delivery', String(xGitHubDelivery));
        }
        if (xGitHubEvent !== undefined && xGitHubEvent !== null) {
            localVarHeaders = localVarHeaders.set('X-GitHub-Event', String(xGitHubEvent));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/webhooks/github`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<GithubWebhookAck>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: requestBody,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
