/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GithubWebhookAck } from '../model/models';
import { ProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ReceiveGithubWebhookRequestParams {
    xHubSignature256: string;
    xGitHubDelivery: string;
    xGitHubEvent: string;
    requestBody: { [key: string]: any; };
}


export interface WebhooksServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Receive a GitHub webhook delivery
     * Inbound-only, called by GitHub\&#39;s webhook infrastructure. No browser client calls this, and it takes no bearer token -- it is documented here anyway because this file is the contract for every HTTP endpoint the backend serves, and this is the one endpoint whose exact header names, verification scheme and status codes most need writing down, since the caller is a third party that cannot be asked to adapt.  **Verification.** GitHub computes HMAC-SHA256 over the *exact raw bytes* of the request body using the shared webhook secret and sends the result as &#x60;X-Hub-Signature-256: sha256&#x3D;&lt;hex&gt;&#x60;. The receiver verifies that signature over the untouched bytes before parsing anything. A missing, malformed, or non-matching signature is a 401 and nothing is recorded. Re-serialising a parsed body would change the bytes (whitespace and key order), so the signed representation is the only one that can be verified -- do not assume a semantically-equal payload will verify.  **Idempotency.** Deliveries are unique on &#x60;X-GitHub-Delivery&#x60;, and GitHub redelivers -- manually from the repository\&#39;s webhook settings, and automatically after some failures. A redelivered id is recorded exactly once: the replay answers 202 with &#x60;status: duplicate&#x60; and publishes no domain event.  **Feature flag.** Disabled by default. While &#x60;app.github-sync.enabled&#x60; is false this path is not mapped at all and answers 404, per CLAUDE.md\&#39;s config-based flags for Phase 7 extensions. When it is true, an unset webhook secret is a startup failure rather than a running receiver that cannot verify anything.  **Scope.** Phase 7a is the receiver only: verify, record, publish a &#x60;GithubDeliveryReceivedEvent&#x60;, stop. What a verified delivery should change on a Project is issue #54 and is deliberately not implemented -- the portfolio\&#39;s prose is hand-curated, so copying a repository description over it would destroy content. 
     * @endpoint post /webhooks/github
* @param requestParameters
     */
    receiveGithubWebhook(requestParameters: ReceiveGithubWebhookRequestParams, extraHttpRequestParams?: any): Observable<GithubWebhookAck>;

}
