/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AboutPage { 
    /**
     * Markdown, with the same subset and the same two-layer rendering as a project\'s `description` (#206): the API stores and returns the source verbatim and never renders it. May be empty -- that is the unwritten state, not an error.  The limit is four times a project description\'s because this is the one long-form page on the site; it is still a hard cap, counted on the source with marks included. 
     */
    body: string;
    /**
     * When the body was last replaced. Set by the migration on creation, so it is never null. 
     */
    updatedAt: string;
}

