/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AboutPageWriteRequest { 
    /**
     * Markdown. An empty string is valid and clears the page.
     */
    body: string;
}

