/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Deliberately minimal -- does not echo the stored message back, just confirms receipt.
 */
export interface ContactMessageAck { 
    id: string;
    createdAt: string;
}

