/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactMessage } from './contactMessage';


export interface ContactMessagePageResponse { 
    page: number;
    size: number;
    totalElements: number;
    totalPages: number;
    content: Array<ContactMessage>;
}

