/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Acknowledgement for a verified GitHub webhook delivery.
 */
export interface GithubWebhookAck { 
    /**
     * Echo of the `X-GitHub-Delivery` header, so a redelivery can be correlated in logs.
     */
    deliveryId: string;
    /**
     * `recorded` -- first time this delivery id was seen; it was stored and a `GithubDeliveryReceivedEvent` was published. `duplicate` -- this delivery id already existed; nothing was stored and no event was published. Both are 202, because from GitHub\'s side both mean \"received, stop retrying\". 
     */
    status: GithubWebhookAck.StatusEnum;
}
export namespace GithubWebhookAck {
    export const StatusEnum = {
        Recorded: 'recorded',
        Duplicate: 'duplicate'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


