/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginResponse { 
    /**
     * JWT bearer token -- pass as `Authorization: Bearer <token>` on subsequent requests.
     */
    token: string;
    expiresAt: string;
}

