/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PasswordResetConfirmBody { 
    /**
     * The raw reset token from the emailed link (compared against the stored hash server-side).
     */
    token: string;
    newPassword: string;
}

