/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PasswordResetValidateBody { 
    /**
     * The raw reset token from the emailed link (compared against the stored hash server-side). Carried in the body rather than as a query parameter so it never reaches a proxy or CDN access log. 
     */
    token: string;
}

