/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * RFC 7807 Problem Details, as returned natively by Spring Boot 3\'s ProblemDetail / @ControllerAdvice.
 */
export interface ProblemDetail { 
    type: string;
    title: string;
    status: number;
    detail?: string;
    instance?: string;
}

