/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tag } from './tag';
import { Link } from './link';


export interface Project { 
    id: string;
    title: string;
    description: string;
    links: Array<Link>;
    images: Array<string>;
    tags: Array<Tag>;
    /**
     * When work on the project started. Null means unspecified.  Distinct from createdAt, which records when the row was entered. Stored at day precision but only ever rendered as month/year -- the underlying source material does not support day-level accuracy, so clients should not present one. The convention is the 1st of the month. 
     */
    startedOn?: string | null;
    /**
     * When work finished. **Null means the project is ongoing**, which is a meaningful value here, not merely missing data. Must not precede startedOn. 
     */
    completedOn?: string | null;
    createdAt: string;
    updatedAt: string;
}

