/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';


export interface ProjectPageResponse { 
    page: number;
    size: number;
    totalElements: number;
    totalPages: number;
    content: Array<Project>;
}

