/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tag } from './tag';
import { Link } from './link';


export interface Project { 
    id: string;
    title: string;
    description: string;
    links: Array<Link>;
    images: Array<string>;
    tags: Array<Tag>;
    createdAt: string;
    updatedAt: string;
}

