/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Link } from './link';


/**
 * Body for both create (POST) and full update (PUT). Tags are given as names -- unknown names are created (upserted), not rejected.
 */
export interface ProjectWriteRequest { 
    title: string;
    description: string;
    links?: Array<Link>;
    images?: Array<string>;
    /**
     * Tag names. Matched case-insensitively against existing tags; new names create a new Tag row.
     */
    tags: Array<string>;
}

