/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationProblemDetailAllOfErrors } from './validationProblemDetailAllOfErrors';


/**
 * ProblemDetail extended with per-field violations.
 */
export interface ValidationProblemDetail { 
    type: string;
    title: string;
    status: number;
    detail?: string;
    instance?: string;
    errors?: Array<ValidationProblemDetailAllOfErrors>;
}

