/**
 * My Site API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationProblemDetailAllOfErrors } from './validationProblemDetailAllOfErrors';


/**
 * ProblemDetail extended with per-field violations.
 */
export interface ValidationProblemDetail { 
    /**
     * Usually absent. Spring\'s ProblemDetail leaves `type` unset unless a handler sets one, and unset fields stay out of the body; no handler here sets one. RFC 9457 says an absent `type` means `about:blank`, so read a missing value that way. Do not treat it as an error. The one body that spells it out is the fixed answer to a request the security firewall refuses, which is written outside Spring MVC; its value is `about:blank` too. 
     */
    type?: string;
    title: string;
    status: number;
    detail?: string;
    instance?: string;
    errors?: Array<ValidationProblemDetailAllOfErrors>;
}

